spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Estoque
    username: postgres
    password: treinamento
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace
